job_name: exp_2

output: ./output/

vgg : /home/alfin/Documents/deep_learning/StyleFlow_DL/weight/vgg_normalised.pth

get_direct: False

read_from_file: True

train_vr: False

n_flow: 10

n_block: 2

no_lu: False

affine: False

lr: 0.0001

lr_decay: 0.00005

max_iter: 187900

lr_steps: [40000,80000,120000]

lr_mults: 0.5

last_iter: -1

total_epoch: 10

batch_size: 1

bn_group: 4

bn_sync_stats: True

workers: 4

mse_weight: 0

style_weight: 1

p_weight: 0.00

content_weight: 0.1

histo_weight: 0

keep_percent: 1

keep_ratio : 0.8

loss: tv_loss

resume: False
